/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for ALOAD_0 Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class ALOAD_0 extends Token {
    public ALOAD_0(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
