/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for CLASS Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class CLASS extends Token {
    public CLASS(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
