/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for CLOSE_PAREN Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class CLOSE_PAREN extends Token {
    public CLOSE_PAREN(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
