/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for DOT Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class DOT extends Token {
    public DOT(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
