/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for DOUBLE_DOT Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class DOUBLE_DOT extends Token {
    public DOUBLE_DOT(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
