/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for END Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class END extends Token {
    public END(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
