/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for ENDLOOP Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class ENDLOOP extends Token {
    public ENDLOOP(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
