/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for GO_TO Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class GO_TO extends Token {
    public GO_TO(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
