/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for GREAT Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class GREAT extends Token {
    public GREAT(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
