/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for IADD Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class IADD extends Token {
    public IADD(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
