/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for IDENTIFIER Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class IDENTIFIER extends Token {
    public IDENTIFIER(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
