/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for IF_ICMPGE Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class IF_ICMPGE extends Token {
    public IF_ICMPGE(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
