/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for IINC Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class IINC extends Token {
    public IINC(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
