/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for ILOAD_1 Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class ILOAD_1 extends Token {
    public ILOAD_1(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
