/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for INT Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class INT extends Token {
    public INT(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
