/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for INTEGER Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class INTEGER extends Token {
    public INTEGER(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
