/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for IRETURN Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class IRETURN extends Token {
    public IRETURN(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
