/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for ISTORE_2 Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class ISTORE_2 extends Token {
    public ISTORE_2(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
