/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for LIMIT Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class LIMIT extends Token {
    public LIMIT(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
