/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for LOCALS Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class LOCALS extends Token {
    public LOCALS(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
