/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for LOOP Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class LOOP extends Token {
    public LOOP(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
