/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for METHOD Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class METHOD extends Token {
    public METHOD(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
