/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for OPEN_PAREN Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class OPEN_PAREN extends Token {
    public OPEN_PAREN(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
