/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for Path1 AST Node type
  * by the ASTNode.java.ftl template
  */
@SuppressWarnings("unused")
public class Path1 extends BaseNode {
}
