/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for PUBLIC Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class PUBLIC extends Token {
    public PUBLIC(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
