/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for RETURN Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class RETURN extends Token {
    public RETURN(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
