/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for SEMICOLON Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class SEMICOLON extends Token {
    public SEMICOLON(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
