/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for SLASH Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class SLASH extends Token {
    public SLASH(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
