/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for STACK Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class STACK extends Token {
    public STACK(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
