/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for Start AST Node type
  * by the ASTNode.java.ftl template
  */
@SuppressWarnings("unused")
public class Start extends BaseNode {
}
