/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for STATIC Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class STATIC extends Token {
    public STATIC(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
