/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for SUPER Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class SUPER extends Token {
    public SUPER(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
