/* Generated by: JavaCC 21 Parser Generator. Do not edit. 
  * Generated Code for VOID Token subclass
  * by the ASTToken.java.ftl template
  */
@SuppressWarnings("unused")
public class VOID extends Token {
    public VOID(TokenType type, JasminParserLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}
